'use server';

/**
 * @fileOverview This file defines a Genkit flow for interacting with a legal AI chatbot.
 *
 * The flow takes a user query as input and returns a legal insight as output.
 * It uses a prompt to generate the legal insight based on the user query.
 *
 * @interface LegalAIChatbotInput - Represents the input schema for the legal AI chatbot.
 * @interface LegalAIChatbotOutput - Represents the output schema for the legal AI chatbot.
 * @function interactWithLegalAIChatbot - A function that calls the legal AI chatbot flow.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const LegalAIChatbotInputSchema = z.object({
  query: z.string().describe('The user query for legal information.'),
});
export type LegalAIChatbotInput = z.infer<typeof LegalAIChatbotInputSchema>;

const LegalAIChatbotOutputSchema = z.object({
  legalInsight: z.string().describe('The legal insight generated by the AI model in Markdown format.'),
});
export type LegalAIChatbotOutput = z.infer<typeof LegalAIChatbotOutputSchema>;

export async function interactWithLegalAIChatbot(input: LegalAIChatbotInput): Promise<LegalAIChatbotOutput> {
  return legalAIChatbotFlow(input);
}

const legalAIChatbotPrompt = ai.definePrompt({
  name: 'legalAIChatbotPrompt',
  input: {schema: LegalAIChatbotInputSchema},
  output: {schema: LegalAIChatbotOutputSchema},
  prompt: `You are a legal AI chatbot designed to provide clear, precise, and actionable legal intelligence.
  Format your response using Markdown, including headings, lists, and bold text for clarity.
  Also, provide some context on past cases or legal history relevant to the query.

  User Query: {{{query}}}

  Legal Insight:`,
});

const legalAIChatbotFlow = ai.defineFlow(
  {
    name: 'legalAIChatbotFlow',
    inputSchema: LegalAIChatbotInputSchema,
    outputSchema: LegalAIChatbotOutputSchema,
  },
  async input => {
    const {output} = await legalAIChatbotPrompt(input);
    return output!;
  }
);
